name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.300
      - name: Run Xunit tests
        run: dotnet test --collect:"XPlat Code Coverage"
        working-directory: ./test/Oatmilk.Tests.Xunit
      - name: Run Nunit tests
        run: dotnet test --collect:"XPlat Code Coverage"
        working-directory: ./test/Oatmilk.Tests.Nunit
      - name: Run MSTest tests
        run: dotnet test --collect:"XPlat Code Coverage"
        working-directory: ./test/Oatmilk.Tests.MSTest
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./test/**/TestResults/**/coverage.cobertura.xml
